<?php

/*
Task 1: Looping through an indexed array

Copy the following array (generated by ChatGPT) to your PHP code:

$shopping_list = array("Apples", "Milk", "Bread", "Eggs", "Chicken");

Then write the code to print the shopping list in the following format:
- Apples
- Milk
- Bread
- Eggs
- Chicken


*/

$shopping_list = array("Apples", "Milk", "Bread", "Eggs", "Chicken");

foreach ($shopping_list as $item) {
    print "- " . $item . "\n";
}