<?php

/*
Task 2: Looping through an associative array

Copy the following array (also generated by ChatGPT) to your PHP code:

$countries_and_capitals = array(
    "United States" => "Washington, D.C.",
    "United Kingdom" => "London",
    "France" => "Paris",
    "Germany" => "Berlin",
    "Italy" => "Rome",
    "Canada" => "Ottawa",
    "Japan" => "Tokyo",
    "Australia" => "Canberra",
    "Brazil" => "Brasília",
    "India" => "New Delhi"
);

Then write the code to loop through the key-value pairs and print each country and its capital in a separate line in the following form: The capital of (country) is (capital). E.g. The capital of France is Paris.
*/

$countries_and_capitals = array(
    "United States" => "Washington, D.C.",
    "United Kingdom" => "London",
    "France" => "Paris",
    "Germany" => "Berlin",
    "Italy" => "Rome",
    "Canada" => "Ottawa",
    "Japan" => "Tokyo",
    "Australia" => "Canberra",
    "Brazil" => "Brasília",
    "India" => "New Delhi"
);

foreach ($countries_and_capitals as $country => $capital) {
    print "The capital of " . $country . " is " . $capital . "\n";
}